set client_min_messages to warning;

-- DANGER: this is NOT how to do it in the real world.
-- `drop schema` INSTANTLY ERASES EVERYTHING.
drop schema "public" cascade;

create schema "public";
CREATE TABLE "users" (
  "userid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" TEXT UNIQUE NOT NULL,
   "email" TEXT NOT NULL,
  "passwordHash" text,
  "createdAt" timestamptz DEFAULT now()
);
CREATE TABLE "questions" (
  "questionid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic" text,
  "los" text,
  "question" text,
  "answer" text,
  "explanation" text,
  "a" text,
  "b" text,
  "c" text,
  "questionNumber" int,
   "userid" INT
);



CREATE TABLE "userAnswers" (
  "answerid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "questionid" int,
  "selectedAnswer" text,
  "isCorrect" boolean,
  "answeredAt" timestamptz
);

CREATE TABLE "mistakes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "questionid" int,
  "createdAt" timestamptz
);

CREATE TABLE "userReviews" (
  "reviewId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userid" int,
  "los" text,
  "addedAt" timestamptz,
  "isAdded" boolean,
  "questionid" int
);

CREATE TABLE "userTasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "questionid" int,
  "userid" int,
  "los" text,
  "addedAt" timestamptz,
  "completedAt" timestamptz,
  "isCompleted" boolean
);

ALTER TABLE "userAnswers" ADD FOREIGN KEY ("userid") REFERENCES "users" ("userid");

ALTER TABLE "userAnswers" ADD FOREIGN KEY ("questionid") REFERENCES "questions" ("questionid");

ALTER TABLE "mistakes" ADD FOREIGN KEY ("userid") REFERENCES "users" ("userid");

ALTER TABLE "mistakes" ADD FOREIGN KEY ("questionid") REFERENCES "questions" ("questionid");

ALTER TABLE "userReviews" ADD FOREIGN KEY ("userid") REFERENCES "users" ("userid");

ALTER TABLE "userReviews" ADD FOREIGN KEY ("questionid") REFERENCES "questions" ("questionid");

ALTER TABLE "userTasks" ADD FOREIGN KEY ("questionid") REFERENCES "questions" ("questionid");

ALTER TABLE "userTasks" ADD FOREIGN KEY ("userid") REFERENCES "users" ("userid");
